# This workflow will install mushr stack and test the sim is functioning properly

name: build-test 

on:
 push:
   branches: [ main, development ]
 pull_request:
   branches: [ main, development ]

jobs:
 build_docker:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:melodic-desktop-full 
    steps:
      - run: "bash -c 'source /opt/ros/melodic/setup.bash && rosnode --help'"
      - run: "rosnode --help"
