# This workflow will install mushr stack and test the sim is functioning properly

name: build-test 

on:
 push:
   branches: [ main, development ]
 pull_request:
   branches: [ main, development ]

jobs:
 build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    steps:
      - uses: ros-tooling/setup-ros@v0.1
        with:
          required-ros-distributions: melodic
      - run: "bash /opt/ros/melodic/setup.bash"
      - run: "ls /opt/ros/melodic"
      - run: "rosnode --help"
